# Generated by Django 2.2.28 on 2022-06-19 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mercaderia',
            fields=[
                ('id_mercaderia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_mercaderia', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('procedencia', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'mercaderia',
                'ordering': ['id_mercaderia'],
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id_nacionalidad', models.AutoField(primary_key=True, serialize=False, verbose_name='Nacionalidad')),
                ('nombre_nacion', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'nacionalidad',
                'ordering': ['nombre_nacion'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('cant_asientos', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
                ('id_nacionalidad', models.ForeignKey(db_column='id_nacionalidad', on_delete=django.db.models.deletion.PROTECT, to='ratpc.Nacionalidad')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('id_nacionalidad', 'placa')},
                'db_table': 'vehiculo',
                'ordering': ['id_vehiculo'],
            },
        ),
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id_transportista', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.CharField(max_length=20)),
                ('tipo_identificacion', models.CharField(max_length=50)),
                ('nombre_persona', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=100)),
                ('tipo_licencia', models.CharField(max_length=30)),
                ('id_nacionalidad', models.ForeignKey(db_column='id_nacionalidad', on_delete=django.db.models.deletion.PROTECT, to='ratpc.Nacionalidad')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('id_usuario', 'id_nacionalidad', 'identificacion')},
                'db_table': 'transportista',
                'ordering': ['id_transportista'],
            },
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id_informe', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_traslacion', models.CharField(max_length=20)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('detalleMercaderia', models.ManyToManyField(to='ratpc.Mercaderia')),
                ('id_transportista', models.ForeignKey(db_column='id_transportista', on_delete=django.db.models.deletion.PROTECT, to='ratpc.Transportista')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('id_vehiculo', models.ForeignKey(db_column='id_vehiculo', on_delete=django.db.models.deletion.PROTECT, to='ratpc.Vehiculo')),
            ],
            options={
                'db_table': 'informe',
                'ordering': ['id_informe'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.CharField(max_length=20)),
                ('tipo_identificacion', models.CharField(max_length=50)),
                ('nombre_persona', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('id_nacionalidad', models.ForeignKey(db_column='id_nacionalidad', on_delete=django.db.models.deletion.PROTECT, to='ratpc.Nacionalidad')),
            ],
            options={
                'unique_together': {('id_nacionalidad', 'identificacion')},
                'db_table': 'persona',
            },
        ),
    ]
