# Generated by Django 2.2.28 on 2022-06-15 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id_informe', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_traslacion', models.CharField(max_length=20)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'informe',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id_nacionalidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_nacion', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'nacionalidad',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.CharField(max_length=20)),
                ('tipo_identificacion', models.CharField(max_length=50)),
                ('nombre_persona', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('id_nacionalidad', models.ForeignKey(db_column='id_nacionalidad', on_delete=django.db.models.deletion.CASCADE, to='ratpc.Nacionalidad')),
            ],
            options={
                'unique_together': {('id_nacionalidad', 'identificacion')},
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('cant_asientos', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
                ('id_nacionalidad', models.ForeignKey(db_column='id_nacionalidad', on_delete=django.db.models.deletion.CASCADE, to='ratpc.Nacionalidad')),
            ],
            options={
                'unique_together': {('id_nacionalidad', 'placa')},
                'db_table': 'vehiculo',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=50, unique=True)),
                ('clave', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('es_agente', models.BooleanField(default=False)),
                ('id_persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ratpc.Persona')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id_transportista', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=100)),
                ('tipo_licencia', models.CharField(max_length=30)),
                ('id_persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ratpc.Persona')),
            ],
            options={
                'db_table': 'transportista',
            },
        ),
        migrations.CreateModel(
            name='Mercaderia',
            fields=[
                ('id_mercaderia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_mercaderia', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('procedencia', models.CharField(max_length=50)),
                ('detalleMercaderia', models.ManyToManyField(to='ratpc.Informe')),
            ],
            options={
                'db_table': 'mercaderia',
            },
        ),
        migrations.AddField(
            model_name='informe',
            name='id_transportista',
            field=models.ForeignKey(db_column='id_transportista', on_delete=django.db.models.deletion.CASCADE, to='ratpc.Transportista'),
        ),
        migrations.AddField(
            model_name='informe',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='ratpc.Usuario'),
        ),
        migrations.AddField(
            model_name='informe',
            name='id_vehiculo',
            field=models.ForeignKey(db_column='id_vehiculo', on_delete=django.db.models.deletion.CASCADE, to='ratpc.Vehiculo'),
        ),
    ]
