# Generated by Django 2.2.28 on 2022-06-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratpc', '0002_auto_20220617_0317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informe',
            options={'ordering': ['id_informe']},
        ),
        migrations.AlterModelOptions(
            name='mercaderia',
            options={'ordering': ['id_mercaderia']},
        ),
        migrations.AlterModelOptions(
            name='transportista',
            options={'ordering': ['id_transportista']},
        ),
        migrations.RemoveField(
            model_name='mercaderia',
            name='detalleMercaderia',
        ),
        migrations.AddField(
            model_name='informe',
            name='detalleMercaderia',
            field=models.ManyToManyField(to='ratpc.Mercaderia'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='es_agente',
            field=models.BooleanField(),
        ),
    ]
