# Generated by Django 2.2.28 on 2022-06-27 23:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ratpc', '0002_delete_persona'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehiculo',
            unique_together={('id_usuario', 'id_nacionalidad', 'placa')},
        ),
    ]
