# Generated by Django 2.2.28 on 2022-06-17 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratpc', '0003_auto_20220617_1856'),
    ]

    operations = [

    ]
